NAME = memrw
SRCS = $(wildcard src/*.c)

# Default target for XiangShan simulation (riscv64-xs)
ARCH ?= riscv64-xs

# Include nexus-am build system. AM_HOME must be set before invoking make.
include $(AM_HOME)/Makefile
